context('Add Address page', () => {
  it('page will load and show all required fields', () => {
    cy.visit('/add-address/cb43e340-883a-497a-aa30-48e37dfd1866')
    cy.url().should('include', '/add-address')
    cy.get('#description').should('exist').should('be.visible')
    cy.get('#buildingName').should('exist').should('be.visible')
    cy.get('#houseNumber').should('exist').should('be.visible')
    cy.get('#streetName').should('exist').should('be.visible')
    cy.get('#district').should('exist').should('be.visible')
    cy.get('#townCity').should('exist').should('be.visible')
    cy.get('#county').should('exist').should('be.visible')
    cy.get('#postcode').should('exist').should('be.visible')
  })

  it('will save all fields and redirect properly when Save is clicked', () => {
    cy.visit('/add-address/2048be31-f7da-4a28-958c-6a9e0691c06a')
    cy.url().should('include', '/add-address')
    cy.get('#description').type('A Description')
    cy.get('#buildingName').type('B Building Name')
    cy.get('#houseNumber').type('C House Number')
    cy.get('#streetName').type('D Street Name')
    cy.get('#district').type('E District')
    cy.get('#townCity').type('F Town City')
    cy.get('#county').type('G County')
    cy.get('#postcode').type('H')
    cy.get('#save-button').should('exist').should('be.visible')
    cy.get('#save-button').click()
    cy.url().should('include', '/witness-details')
  })

  it('will return to witness details screen when cancel is clicked', () => {
    cy.visit('/add-address/da1ad869-b29b-43e8-bfdc-fb15ce3934d7')
    cy.url().should('include', '/add-address')
    cy.get('#cancel-button').should('exist').should('be.visible')
    cy.get('#cancel-button').click()
    cy.url().should('include', '/witness-details')
  })

  it('validation will trigger when none of description, number or name is present', () => {
    cy.visit('/add-address/68cfc760-1d4d-458c-8db5-c84ec0179026')
    cy.url().should('include', '/add-address')
    cy.get('#streetName').type('D Street Name')
    cy.get('#district').type('E District')
    cy.get('#townCity').type('F Town City')
    cy.get('#county').type('G County')
    cy.get('#postcode').type('H Postcode')
    cy.get('#save-button').should('exist').should('be.visible')
    cy.get('#save-button').click()
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.get('#description-error')
      .should('exist')
      .should('contain.text', 'At least 1 out of [Description, Building Name, Address Number] must be present')
    cy.get('#buildingName-error')
      .should('exist')
      .should('contain.text', 'At least 1 out of [Description, Building Name, Address Number] must be present')
    cy.get('#houseNumber-error')
      .should('exist')
      .should('contain.text', 'At least 1 out of [Description, Building Name, Address Number] must be present')
  })

  it('validation will trigger when street, town or postcode is left blank', () => {
    cy.visit('/add-address/452750f1-dcfd-4d79-a269-09dfb1b9f7e4')
    cy.url().should('include', '/add-address')
    cy.get('#description').type('A Description')
    cy.get('#buildingName').type('B Building Name')
    cy.get('#houseNumber').type('C House Number')
    cy.get('#district').type('E District')
    cy.get('#save-button').should('exist').should('be.visible')
    cy.get('#save-button').click()
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.get('#streetName-error')
      .should('exist')
      .should('contain.text', 'Street Name : This is a required value, please enter a value')
    cy.get('#townCity-error')
      .should('exist')
      .should('contain.text', 'Town/City : This is a required value, please enter a value')
    cy.get('#postcode-error')
      .should('exist')
      .should('contain.text', 'Postcode : This is a required value, please enter a value')
  })

  it('page will load and show previously entered data fields', () => {
    cy.visit('/add-address/44fbdcf5-0e07-44b8-94aa-2e685798af70')
    cy.url().should('include', '/add-address')
    cy.get('#description').should('have.value', 'Descriptive Name')
    cy.get('#buildingName').should('have.value', 'Descriptive Tower')
    cy.get('#houseNumber').should('have.value', '33')
    cy.get('#streetName').should('have.value', 'Descriptive Street')
    cy.get('#district').should('have.value', 'Descriptive District')
    cy.get('#townCity').should('have.value', 'Descriptive Town')
    cy.get('#county').should('have.value', 'Descriptive County')
    cy.get('#postcode').should('have.value', 'DE54 1BE')
  })
})
