context('Check your answers', () => {
  it('Basic Details populated', () => {
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.url().should('include', '/check-your-report')
    cy.get('#page-title').should('contain.text', 'Breach Notice - Check Your Answers')
    cy.get('#change-basic-details').should('exist')
    cy.get('#cya-link-title-and-name').should('not.exist')
    cy.get('#cya-link-crn').should('not.exist')
    cy.get('#cya-link-postal-address').should('not.exist')
    cy.get('#cya-link-date-of-birth').should('not.exist')
    cy.get('#offenderName').should('contain.text', 'Billy The Kid')
    cy.get('#crn').should('contain.text', 'X012345')
    cy.get('#postal-address-building-name').should('contain.text', 'Older Postal Address')
    cy.get('#postal-address-building-number-street-name')
      .should('contain.text', '1')
      .and('contain.text', 'Older Postal Address')
    cy.get('#postal-address-district').should('contain.text', 'Postal District')
    cy.get('#postal-address-town').should('contain.text', 'Postal Town')
    cy.get('#postal-address-county').should('contain.text', 'Postal County')
    cy.get('#postal-address-postcode').should('contain.text', 'AA1 1AA')
    cy.get('#dob').should('contain.text', '17/03/1980')
    cy.get('#change-basic-details').click()
    cy.url().should('include', '/basic-details/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
  })

  it('basic details not populated', () => {
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.url().should('include', '/check-your-report')
    cy.get('#page-title').should('contain.text', 'Breach Notice - Check Your Answers')
    cy.get('#change-basic-details').should('exist')
    cy.get('#cya-link-title-and-name').should('exist')
    cy.get('#cya-link-crn').should('exist')
    cy.get('#cya-link-postal-address').should('exist')
    cy.get('#cya-link-date-of-birth').should('exist')
    cy.get('#change-basic-details').click()
    cy.url().should('include', '/basic-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-title-and-name').click()
    cy.url().should('include', '/basic-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-crn').click()
    cy.url().should('include', '/basic-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-postal-address').click()
    cy.url().should('include', '/basic-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-date-of-birth').click()
    cy.url().should('include', '/basic-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
  })

  it('Basic Details not saved', () => {
    cy.visit('/check-your-report/9c7f4a6d-3e2b-4d8f-9b61-2c7f5a9e1d34')
    cy.url().should('include', '/check-your-report')
    cy.get('#change-basic-details').should('not.exist')
    cy.get('#cya-link-title-and-name').should('not.exist')
    cy.get('#cya-link-crn').should('not.exist')
    cy.get('#cya-link-postal-address').should('not.exist')
    cy.get('#cya-link-date-of-birth').should('not.exist')
  })

  it('Offence Details not saved', () => {
    cy.visit('/check-your-report/9c7f4a6d-3e2b-4d8f-9b61-2c7f5a9e1d34')
    cy.url().should('include', '/check-your-report')
    cy.get('#change-offence-details').should('not.exist')
    cy.get('#cya-link-main-offence').should('not.exist')
    cy.get('#cya-link-sentencing-court').should('not.exist')
    cy.get('#cya-link-sentence-date').should('not.exist')
    cy.get('#cya-link-imposed-sentence').should('not.exist')
    cy.get('#cya-link-sentence-length').should('not.exist')
    cy.get('#cya-link-requirements').should('not.exist')
    cy.get('#cya-link-amendments').should('not.exist')
    cy.get('#change-offence-details').should('not.exist')
  })

  it('Offence Details populated', () => {
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.url().should('include', '/check-your-report')
    cy.get('#change-offence-details').should('exist')
    cy.get('#cya-link-main-offence').should('not.exist')
    cy.get('#cya-link-sentencing-court').should('not.exist')
    cy.get('#cya-link-sentence-date').should('not.exist')
    cy.get('#cya-link-imposed-sentence').should('not.exist')
    cy.get('#cya-link-sentence-length').should('not.exist')
    cy.get('#cya-link-requirements').should('not.exist')
    cy.get('#cya-link-amendments').should('not.exist')
    cy.get('#main-offence').should('contain.text', 'Offence Description')
    cy.get('#sentencing-court').should('contain.text', 'TEST style Court')
    cy.get('#sentence-date').should('contain.text', '01/04/2025')
    cy.get('#sentence-imposed').should('contain.text', 'Sentence Imposed Description')
    cy.get('#sentence-length').should('contain.text', '20 Days')
    cy.get('#requirement-info-1')
      .should('contain.text', 'Requirement Type Main Category Description')
      .and('contain.text', '20 Months')
      .and('contain.text', '12 Months')
    cy.get('#requirement-info-2')
      .should('contain.text', 'Another Main Category Description')
      .and('contain.text', '2 Months')
      .and('contain.text', '1 Months')
    cy.get('#amendment-info-1')
      .should('contain.text', 'TEST DETAILS')
      .and('contain.text', 'TEST REASON')
      .and('contain.text', '2026-01-14')
    cy.get('#amendment-info-2')
      .should('contain.text', 'SECOND DETAILS')
      .and('contain.text', 'SECOND REASON')
      .and('contain.text', '2025-12-25')
    cy.get('#change-offence-details').click()
    cy.url().should('include', '/offence-details/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
  })

  it('Offence Details not populated', () => {
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.url().should('include', '/check-your-report')
    cy.get('#page-title').should('contain.text', 'Breach Notice - Check Your Answers')
    cy.get('#change-offence-details').should('exist')
    cy.get('#cya-link-main-offence').should('exist')
    cy.get('#cya-link-sentencing-court').should('exist')
    cy.get('#cya-link-sentence-date').should('exist')
    cy.get('#cya-link-imposed-sentence').should('exist')
    cy.get('#cya-link-sentence-length').should('exist')
    cy.get('#change-offence-details').click()
    cy.url().should('include', '/offence-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-main-offence').click()
    cy.url().should('include', '/offence-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-sentencing-court').click()
    cy.url().should('include', '/offence-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-sentence-date').click()
    cy.url().should('include', '/offence-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-imposed-sentence').click()
    cy.url().should('include', '/offence-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-sentence-length').click()
    cy.url().should('include', '/offence-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-requirements').click()
    cy.url().should('include', '/offence-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-amendments').click()
    cy.url().should('include', '/offence-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
  })

  it('Failures and Enforcement not saved', () => {
    cy.visit('/check-your-report/9c7f4a6d-3e2b-4d8f-9b61-2c7f5a9e1d34')
    cy.url().should('include', '/check-your-report')
    cy.get('#change-failures-and-enforcement').should('not.exist')
    cy.get('#cya-link-why-in-breach').should('not.exist')
    cy.get('#cya-link-steps-to-prevent-breach').should('not.exist')
    cy.get('#cya-link-risk-of-harm-changed').should('not.exist')
    cy.get('#cya-link-please-describe-harm-changed').should('not.exist')
    cy.get('#cya-link-diversity-confirmation').should('not.exist')
    cy.get('#cya-link-recommendation').should('not.exist')
    cy.get('#cya-link-supporting-comments').should('not.exist')
  })

  it('Failures and Enforcement populated', () => {
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.url().should('include', '/check-your-report')
    cy.get('#cya-link-why-in-breach').should('not.exist')
    cy.get('#cya-link-steps-to-prevent-breach').should('not.exist')
    cy.get('#cya-link-risk-of-harm-changed').should('not.exist')
    cy.get('#cya-link-please-describe-harm-changed').should('not.exist')
    cy.get('#cya-link-diversity-confirmation').should('not.exist')
    cy.get('#cya-link-recommendation').should('not.exist')
    cy.get('#cya-link-supporting-comments').should('not.exist')
    cy.get('#why-in-breach').should('contain.text', 'Breach reason details')
    cy.get('#steps-to-prevent-breach').should('contain.text', 'Steps to prevent breach details')
    cy.get('#risk-changed').should('contain.text', 'Yes')
    cy.get('#risk-history').should('contain.text', 'Risk history details comments')
    cy.get('#diversity-confirmation').should('contain.text', 'Confirmed')
    cy.get('#recommendations').should('contain.text', 'The order is continued')
    cy.get('#supporting-comments').should('contain.text', 'The order is continues supporting comments')
    cy.get('#change-failures-and-enforcement').click()
    cy.url().should('include', '/failures/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
  })

  it('Failures and Enforcement not populated', () => {
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.url().should('include', '/check-your-report')
    cy.get('#page-title').should('contain.text', 'Breach Notice - Check Your Answers')
    cy.get('#change-failures-and-enforcement').should('exist')
    cy.get('#cya-link-why-in-breach').should('exist')
    cy.get('#cya-link-steps-to-prevent-breach').should('exist')
    cy.get('#cya-link-risk-of-harm-changed').should('exist')
    cy.get('#cya-link-please-describe-harm-changed').should('exist')
    cy.get('#cya-link-diversity-confirmation').should('exist')
    cy.get('#cya-link-recommendation').should('exist')
    cy.get('#cya-link-supporting-comments').should('exist')
    cy.get('#change-failures-and-enforcement').click()
    cy.url().should('include', '/failures/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-why-in-breach').click()
    cy.url().should('include', '/failures/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-steps-to-prevent-breach').click()
    cy.url().should('include', '/failures/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-risk-of-harm-changed').click()
    cy.url().should('include', '/failures/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-please-describe-harm-changed').click()
    cy.url().should('include', '/failures/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-diversity-confirmation').click()
    cy.url().should('include', '/failures/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-recommendation').click()
    cy.url().should('include', '/failures/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-supporting-comments').click()
    cy.url().should('include', '/failures/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
  })

  it('RO and witness not saved', () => {
    cy.visit('/check-your-report/9c7f4a6d-3e2b-4d8f-9b61-2c7f5a9e1d34')
    cy.url().should('include', '/check-your-report')
    cy.get('#cya-link-ro-title-and-full-name').should('not.exist')
    cy.get('#cya-link-probation-area').should('not.exist')
    cy.get('#cya-link-office-address').should('not.exist')
    cy.get('#cya-link-ro-telephone-number').should('not.exist')
    cy.get('#cya-link-ro-email-address').should('not.exist')
    cy.get('#cya-link-witness-availability').should('not.exist')
  })

  it('RO and witness details populated', () => {
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.url().should('include', '/check-your-report')
    cy.get('#change-ro-and-witness-details').should('exist')
    cy.get('#cya-link-ro-title-and-full-name').should('not.exist')
    cy.get('#cya-link-probation-area').should('not.exist')
    cy.get('#cya-link-office-address').should('not.exist')
    cy.get('#cya-link-ro-telephone-number').should('not.exist')
    cy.get('#cya-link-ro-email-address').should('not.exist')
    cy.get('#cya-link-witness-availability').should('not.exist')
    cy.get('#ro-full-name').should('contain.text', 'Mr Ro Test')
    cy.get('#probation-area').should('contain.text', 'London')
    cy.get('#work-address-building-name').should('contain.text', 'Work Address')
    cy.get('#work-address-building-number-street-name')
      .should('contain.text', '2')
      .and('contain.text', 'Older Postal Address')
    cy.get('#work-address-district').should('contain.text', 'District Address')
    cy.get('#work-address-town').should('contain.text', 'Old Town')
    cy.get('#work-address-county').should('contain.text', 'County')
    cy.get('#work-address-postcode').should('contain.text', 'BB2 2BB')
    cy.get('#ro-telephone-number').should('contain.text', '0123456789')
    cy.get('#ro-email-address').should('contain.text', 'ro_email@email.com')
    cy.get('#witness-availability').should('contain.text', 'Witness availability details')
    cy.get('#change-ro-and-witness-details').click()
    cy.url().should('include', '/witness-details/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
  })

  it('RO and witness details not populated', () => {
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.url().should('include', '/check-your-report')
    cy.get('#page-title').should('contain.text', 'Breach Notice - Check Your Answers')
    cy.get('#change-ro-and-witness-details').should('exist')
    cy.get('#cya-link-ro-title-and-full-name').should('exist')
    cy.get('#cya-link-probation-area').should('exist')
    cy.get('#cya-link-office-address').should('exist')
    cy.get('#cya-link-ro-telephone-number').should('exist')
    cy.get('#cya-link-ro-email-address').should('exist')
    cy.get('#cya-link-witness-availability').should('exist')
    cy.get('#cya-link-witness-availability').click()
    cy.url().should('include', '/witness-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-ro-title-and-full-name').click()
    cy.url().should('include', '/witness-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-probation-area').click()
    cy.url().should('include', '/witness-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-office-address').click()
    cy.url().should('include', '/witness-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-ro-telephone-number').click()
    cy.url().should('include', '/witness-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-ro-email-address').click()
    cy.url().should('include', '/witness-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-witness-availability').click()
    cy.url().should('include', '/witness-details/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
  })

  it('Compliance to date populated', () => {
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.url().should('include', '/check-your-report')
    cy.get('#change-compliance').should('exist')
    cy.get('#compliance').should('contain.text', 'Description of compliance with the whole order to date')
    cy.get('#signature').should('contain.text', 'Ro Test 10/02/2026')
    cy.get('#change-compliance').click()
    cy.url().should('include', '/compliance/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
  })

  it('Compliance not populated', () => {
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.url().should('include', '/check-your-report')
    cy.get('#change-compliance').should('exist')
    cy.get('#cya-link-compliance').should('exist')
    cy.get('#cya-link-signature').should('exist')
    cy.get('#cya-link-compliance').click()
    cy.url().should('include', '/compliance/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.get('#cya-link-signature').click()
    cy.url().should('include', '/compliance/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
  })

  it('Compliance not saved', () => {
    cy.visit('/check-your-report/9c7f4a6d-3e2b-4d8f-9b61-2c7f5a9e1d34')
    cy.url().should('include', '/check-your-report')
    cy.get('#change-compliance').should('not.exist')
    cy.get('#cya-link-compliance').should('not.exist')
    cy.get('#cya-link-signature').should('not.exist')
  })

  it('I can see publish button only when all details are populated', () => {
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.url().should('include', '/check-your-report')
    cy.get('#publish').should('exist')
    cy.visit('/check-your-report/e3b2f8c1-6a4d-4c92-9f27-8d5a1c7e4b90')
    cy.url().should('include', '/check-your-report')
    cy.get('#publish').should('not.exist')
  })

  it('I can delete draft', () => {
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.url().should('include', '/check-your-report')
    cy.get('#delete-btn').should('exist')
    cy.get('#delete-btn').click()
    cy.url().should('include', '/confirm-delete/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
    cy.visit('/check-your-report/9de01b5e-30bd-4989-b0ad-29d5df2b70cs')
  })
})
