context('Sign and Send Page', () => {
  it('Sign and Send with no signature', () => {
    cy.visit('/sign-and-send/01fee60f-63c1-495b-b36e-33aff0e429e4')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('#sign-button').should('exist')
    cy.get('#clear-signature-button').should('not.exist')
    cy.get('#sign-button').should('exist')
    cy.get('#signature').should('not.exist')
  })

  it('Sign and Send with signature', () => {
    cy.visit('/sign-and-send/6fcb76c7-f06c-4aac-92a9-fada15781694')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('#sign-button').should('not.exist')
    cy.get('#clear-signature-button').should('exist')
    cy.get('#sign-button').should('not.exist')
    cy.get('#signature').should('exist').should('contain.text', 'Sign and Send 01/01/1970')
  })

  it('Can See and Select who is sending fields', () => {
    cy.visit('/sign-and-send/5cacfff9-dbe0-4e8c-9d3e-f10ac302b502')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('#whoIsSendingTheForm').should('exist')
    cy.get('input[type="radio"][value="RO"]').should('exist')
    cy.get('input[type="radio"][value="USER"]').should('exist')
    cy.get('input[type="radio"][value="RO"]').check()
    cy.get('input[type="radio"][value="RO"]').should('be.checked')
    cy.get('input[type="radio"][value="USER"]').should('not.be.checked')
    cy.get('input[type="radio"][value="USER"]').check()
    cy.get('input[type="radio"][value="RO"]').should('not.be.checked')
    cy.get('input[type="radio"][value="USER"]').should('be.checked')
  })

  it('Validation when no radio button selected', () => {
    cy.visit('/sign-and-send/95e35d1a-fefe-4d4f-aaa4-a175ced57e1e')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('#continue-button').click()
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.get('#whoIsSendingTheForm-error')
      .should('exist')
      .should('contain.text', 'Please select who is sending this document before leaving this screen')
  })

  it('Can See pre-populated who, officer name, email, telephone fields', () => {
    cy.visit('/sign-and-send/2015734f-390c-49e4-8401-fde750c38524')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('#whoIsSendingTheForm').should('exist')
    cy.get('input[type="radio"][value="RO"]').should('be.checked')
    cy.get('#name').should('exist').should('contain.text', 'Sign and\n             Send\n               Officer')
    cy.get('#officer-email-address').should('exist').should('contain.text', 'SignSendOfficer@email.com')
    cy.get('#signature').should('exist').should('contain.text', 'Sign and Send 01/01/1970')
    cy.get('#telephone-number').should('exist').should('contain.text', '01234567891')
  })

  it('Continue saves and navigates away', () => {
    cy.visit('/sign-and-send/a66b643e-0bdc-4599-aa63-74e6073767f3')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('input[type="radio"][value="RO"]').check()
    cy.get('#continue-button').should('exist')
    cy.get('#continue-button').click()
    cy.url().should('include', '/check-your-report/a66b643e-0bdc-4599-aa63-74e6073767f3')
  })

  it('should return to check your report if came from check your report', () => {
    cy.visit('/sign-and-send/ee7140bc-ae6e-434f-980a-6c648d8248d5?returnTo=check-your-report')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('input[type="radio"][value="RO"]').check()
    cy.get('#continue-button').should('exist')
    cy.get('#continue-button').click()
    cy.url().should('include', '/check-your-report/ee7140bc-ae6e-434f-980a-6c648d8248d5')
  })

  it('Refresh from delius reloads', () => {
    cy.visit('/sign-and-send/f0fa9a46-8f64-4459-b48a-7e9e2860737c')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('#refresh-from-ndelius--button').should('exist')
    cy.get('#refresh-from-ndelius--button').click()
    cy.url().should('include', '/sign-and-send/f0fa9a46-8f64-4459-b48a-7e9e2860737c')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
  })

  it('close button displays message', () => {
    cy.intercept('POST', '/sign-and-send/**').as('saveAndCloseRequest')
    cy.visit('/sign-and-send/b548e8b6-d1ff-43e7-b3fa-b0faeb77a3dd')
    cy.url().should('include', '/sign-and-send')
    cy.get('#page-title').should('contain.text', 'Breach Report CO SSO - Sign and Send')
    cy.get('input[type="radio"][value="RO"]').check()
    cy.get('#close-button').click()
    cy.wait('@saveAndCloseRequest').then(({ request }) => {
      const body = new URLSearchParams(request.body)
      expect(body.get('action')).to.equal('saveProgressAndClose')
    })
    cy.contains('You can now safely close this window').should('be.visible')
    cy.get('#page-title').should('not.exist')
  })
})
