---
# Per environment values which override defaults in hmpps-breach-report-co-sso-ui/values.yaml

generic-service:
  ingress:
    host: cosso-ui-prod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://cosso-ui-prod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    COSSO_API_URL: "https://cosso-api-prod.hmpps.service.justice.gov.uk"
    PROBATION_ACCESS_CONTROL_URL: "https://probation-access-control.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "false"
    NDELIUS_INTEGRATION_URL: "https://cosso-and-delius.hmpps.service.justice.gov.uk"
    NDELIUS_DEEPLINK_URL: "https://ndelius.probation.service.justice.gov.uk/NDelius-war/delius/JSP/deeplink.xhtml"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - unilink_staff
      - probation # for production staff

generic-prometheus-alerts:
  alertSeverity: hmpps-co-sso-notifications
